// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaG_6q5TWcqX5EoVrcinYDtFxtELkHhNY',
    appId: '1:171350712043:web:044dbe6dfb030b2210a8ae',
    messagingSenderId: '171350712043',
    projectId: 'internship-d25e0',
    authDomain: 'internship-d25e0.firebaseapp.com',
    storageBucket: 'internship-d25e0.appspot.com',
    measurementId: 'G-KNMSM6Y0BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvbb-e1nFfziDKLX2CLU_RoTR7IS7vWao',
    appId: '1:171350712043:android:fb3be76c6b98fd4710a8ae',
    messagingSenderId: '171350712043',
    projectId: 'internship-d25e0',
    storageBucket: 'internship-d25e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUHPet4coaLS4F7pcaBMhZKDI0mItiQYg',
    appId: '1:171350712043:ios:cfa6cfb488b9e32410a8ae',
    messagingSenderId: '171350712043',
    projectId: 'internship-d25e0',
    storageBucket: 'internship-d25e0.appspot.com',
    iosBundleId: 'com.example.goprogsInternshipTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUHPet4coaLS4F7pcaBMhZKDI0mItiQYg',
    appId: '1:171350712043:ios:cfa6cfb488b9e32410a8ae',
    messagingSenderId: '171350712043',
    projectId: 'internship-d25e0',
    storageBucket: 'internship-d25e0.appspot.com',
    iosBundleId: 'com.example.goprogsInternshipTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaG_6q5TWcqX5EoVrcinYDtFxtELkHhNY',
    appId: '1:171350712043:web:71fb71dde65c466310a8ae',
    messagingSenderId: '171350712043',
    projectId: 'internship-d25e0',
    authDomain: 'internship-d25e0.firebaseapp.com',
    storageBucket: 'internship-d25e0.appspot.com',
    measurementId: 'G-HJ1SX51CRP',
  );
}
